language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - python manage.py wait_for_db &&
    python manage.py migrate &&
    docker-compose run app python manage.py test && flake8